### ISSUE TITLE
Page up and page down

### ISSUE THREAD

**Issue by myint** [theabraham/chex#3]
It would be nice if the page up and page down matched Vim's `ctrl-b` and `ctrl-f`, respectively.

**Comment by myint** [comment]
Two years seems long enough. Never mind then.

**Comment by joebentley** [comment]
I fixed this on my fork a while ago just for fun, seems like there has been no further maintenance on this project but I might submit a pull request or you can if you want with my code.

https://github.com/unanimousarc/chex/commit/04a1891fd7133b54338855839bded48373186b00

**Comment by myint** [comment]
Cool.

**Comment by theabraham** [comment]
Hey, sorry for the slow response. This was just a toy I built out, and I haven't had time to add to it really. If you submit a PR for that change though, I'd be happy to merge it!
